### PR TITLE
link to revised Schurch et al.

### PR DESCRIPTION
**Pull request by mikelove**
:-)

### CODE REVIEW

**Comment by gjbarton** [comment]
Indeed  :-)

Sigh...

G.

On 15/06/2016 19:49, Mike Love wrote:

:-)

---

You can view, comment on, or merge this pull request online at:

  https://github.com/bartongroup/profDGE48/pull/1

Commit Summary
-   link to revised Schurch et al.

File Changes
-   M README.mdhttps://github.com/bartongroup/profDGE48/pull/1/files#diff-0 (2)

Patch Links:
-   https://github.com/bartongroup/profDGE48/pull/1.patch
-   https://github.com/bartongroup/profDGE48/pull/1.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHubhttps://github.com/bartongroup/profDGE48/pull/1, or mute the threadhttps://github.com/notifications/unsubscribe/ARBUyF9FIgo5rkJtKYrrER2kmiMcRLvJks5qMElNgaJpZM4I2rGN.

## 

Geoff Barton | Professor of Bioinformatics | Head of Division of Computational Biology
School of Life Sciences | University of Dundee, Scotland, UK | g.j.barton@dundee.ac.ukmailto:g.j.barton@dundee.ac.uk
Tel: +44 1382 385860 | www.compbio.dundee.ac.ukhttp://www.compbio.dundee.ac.uk | twitter: @gjbarton

The University of Dundee is registered Scottish charity: No.SC015096

The University of Dundee is a registered Scottish Charity, No: SC015096

**Comment by mikelove** [comment]
I swear i didn't come here looking for old links! 

We're going to be using the dataset in the CSAMA summer course to teach method evaluation 

Will share afterward!

**Comment by gjbarton** [comment]
Hahaha!  If you do come across any more of these links lurking around I'm sure you will let us know!  We'll use the doi in future to avoid such problems!

It is great that you will be using the dataset in the course.  Thanks for letting us know.  I look forward to hearing how it goes.

All the best,

Geoff.

On 15/06/2016 22:19, Mike Love wrote:

I swear i didn't come here looking for old links!

We're going to be using the dataset in the CSAMA summer course to teach method evaluation

Will share afterward!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHubhttps://github.com/bartongroup/profDGE48/pull/1#issuecomment-226323503, or mute the threadhttps://github.com/notifications/unsubscribe/ARBUyAcnh0IrtS93tTy4pBtp7xtHKjwzks5qMGxvgaJpZM4I2rGN.

## 

Geoff Barton | Professor of Bioinformatics | Head of Division of Computational Biology
School of Life Sciences | University of Dundee, Scotland, UK | g.j.barton@dundee.ac.ukmailto:g.j.barton@dundee.ac.uk
Tel: +44 1382 385860 | www.compbio.dundee.ac.ukhttp://www.compbio.dundee.ac.uk | twitter: @gjbarton

The University of Dundee is registered Scottish charity: No.SC015096

The University of Dundee is a registered Scottish Charity, No: SC015096

**Comment by nickschurch** [comment]
Actually, on that note, lets use the DOI directly here rather than use a link to the journal.... now I wonder if you can edit people pull requests?...

OK, I don't think you can edit peoples pull requests so I've just changed the link directly. I'll close this now. Thanks Mike.

**Comment by nickschurch** [comment]
Closed because I've updated the link with a doi link (as Chris suggested) rather than use a direct link to the journal at all. This will always point at the most up to date version.

**Pull request closed without merging**
